/*
    in chapter 3, we will look at listings generated by a disassembler, a program that converts an executable program file back to a more readable ascii form. these files contain many hexadecimal numbers, typically representing values in two's complement form. being able to recognize these numbers and understand their significance (for example, whether they are negative or positive) is an important skill.
    
    for the lines labeled a-i (on the right), in the following listing, convert the hexadecimal values (in 32-bit two's complement form) shown to the right of the instruction names (sub, mov, and add) into their decimal equivalent
*/

main:
    sub $0x2e0, %rsp               ;A. 0x02E0 -> (2 * 16^2) + (14 * 16^0)              -> 736
    mov -0x58(%rsp), %rax          ;B.-0x0058 ->-((5 * 16^1) + (8 * 16^0))             -> -88 
    add 0x28(%rdi), %rax           ;C. 0x0028 -> (2 * 16^1) + (8 * 16^0)               -> 40
    mov %rax, -0x30(%rsp)          ;D. 0x0030 -> (3 * 16^1)                            -> 48
    mov 0x78(%rsp), %rax           ;E. 0x0078 -> (7 * 16^1) + (8 * 16^0)               -> 120
    mov %rax, 0x88(%rdi)           ;F. 0x0088 -> (8 * 16^1) + (8 * 16^0)               -> 136
    mov 0x1f8(%rsp), %rax          ;G. 0x01F8 -> (1 * 16^2) + (15 * 16^1) + (8 x 16^0) -> 504

    add 0x8(%rsp), %rax            
    mov %rax, 0xc0(%rsp)           ;H. 0x00C0 -> (12 * 16^1)                           -> 192

    mov -0x48(%rsp, %rdx, 8), %rax ;I.-0x0048 ->-((4 * 16^1) + (8 * 16^0))             -> -72
