/*
    We can represent a bit pattern of length w = 4 with a single hex digit. For a two's-complement interpretation of these digits, fill in the following table to determine the additive inverses of the digits shown:
         
        x           -(^t)(_4)(x)
        Hex	Decimal	Decimal	Hex
        0	0	    0	    0
        5	5	    -5	    B
        8	-8	    -8	    8
        D	-3	    3	    3
        F	-1	    1       1


    What do you observe about the bit patterns generated by two's-complement and unsigned (Problem 2.28) negation?

        i briefly fail to recall that the negation of the numbers was against a 4-bit number representation (as thus, negation is not in the usual decimal sense, but against the group of two-complement numbers -8 to 7), but i've quickly revised the table to reflect this

        one interesting thing i would like to mention is how (like i mentioned in describing the failing of tsub_ok() in a previous problem) the negation of 0x8 results in 0x8, both of which are represented as -8 in decimal form.
*/